### ISSUE TITLE
Multiple setup questions found with map string(Power Down Enable)

### ISSUE THREAD

**Issue by mmunnk** [amitxv/SCEWIN#1]
### Motherboard model

ASUS B450M-ii

### Version

ver 5.04.1144

### Command type

SCEWIN_64.exe /i /ms "Power Down Enable" /qv 0x0 /lang en-US

### Log file

![image](https://github.com/ab3lkaizen/SCEHUB/assets/97799344/2c4859a1-4284-431e-88e7-711c14ac6a5e)

### Possible solution

Is there a command that applies a setting to every key with the same name?

**Comment by ab3lkaizen** [comment]
Unfortunately, no. If multiple instances of a map string exist in the BIOS, both reading and writing those setup questions are prevented. These are considered ambiguous for `UEFI 2.0`. However, `UEFI 2.1` should be able to distinguish identical setup questions with the help of _tokens_. Although, I didn't find any option that allows the user to provide the token, resulting in the same error.

**Comment by firasdib** [comment]
How do you then update values which have multiple setup questions?
