### ISSUE TITLE
Empty `nvram.txt`

### ISSUE THREAD

**Issue by Nkaslqi** [amitxv/SCEWIN#3]
### Motherboard model

MSI MS-15M2

### Version

ver 5.05.01.0002

### Command type

after installing it with "python DL_SCEWIN.py", i just ran the Export.bat as administrator

### Log file

![Screenshot 2024-11-03 171831](https://github.com/user-attachments/assets/db922430-da93-4ff4-b4ff-9d8c7acf3553)
![Screenshot 2024-11-03 171845](https://github.com/user-attachments/assets/36b8fc8d-6b99-47fd-8f9b-b85faabc0afa)

the problem is that the nvram.txt is 1kb with almost nothing inside

### Possible solution

Im on laptop btw

**Comment by ab3lkaizen** [comment]
I have taken a look at the BIOS of your laptop. The issue you are experiencing is [this](https://github.com/ab3lkaizen/SCEHUB?tab=readme-ov-file#warning-hii-data-does-not-have-setup-questions-information): `HII resources` are not published, so SCEWIN has no data to work with. Additionally, the various `VarStore`s do not have the appropriate **attributes** and are therefore inaccessible from the operating system.
I will publish a solution for this soon, but it will require you to flash a modified BIOS, which has its own risks involved. Alternatively, you could use [setupvar-builder](https://github.com/ab3lkaizen/setupvar-builder).
