### ISSUE TITLE
Blank `nvram.txt` -- no BIOS settings

### ISSUE THREAD

**Issue by bruholox** [amitxv/SCEWIN#5]
when i do export that pops up, been looking through the internet for about 2 hours and theres nothing i can find

**Comment by bruholox** [comment]
HIICrc32= 7B5E4A7F also this in the bios settings txt thing

**Comment by bruholox** [comment]
no inside the nvram.txt, it doesnt show my hidden bios settings

**Comment by bruholox** [comment]
it only shows HIICrc32= 7B5E4A7F

**Comment by bruholox** [comment]
![image_2023-12-11_074205086](https://github.com/amitxv/SCEWIN/assets/126908120/adf23019-35ce-4117-8ded-8a03c783cabc)
![image_2023-12-11_074327810](https://github.com/amitxv/SCEWIN/assets/126908120/75ea70f5-b5f0-4578-b63b-f3302d067a11)
![image_2023-12-11_074350596](https://github.com/amitxv/SCEWIN/assets/126908120/e300fcb3-1a39-4673-8e2a-e160a283c40c)
sorry for the late response but here.

**Comment by ab3lkaizen** [comment]
Thanks! I have some ideas, but you would need to flash a modded BIOS. Is there any way you could recover in case the flash goes wrong? -- Do you have an SPI programmer (e.g. CH341A) handy?
Please contact me on Discord: `ab3lkaizen`
The outcome will also be posted here, it's just easier to communicate via Discord

**Comment by bruholox** [comment]
I don't think I could flash or any of the others tbh, If it requires that much stuff to do, I'm fine with just sticking without optimizing the hidden bios.

**Comment by ab3lkaizen** [comment]
Outcome: My theory could not be tested as the user does not have the proper tools. If someone is having the same issue and is interested in fixing it, the issue can be reopened.
