### ISSUE TITLE
"Unmatched question" on many settings due to their auto value being present in the Setup Question field on MSI boards

### ISSUE THREAD

**Issue by potat0nerd** [amitxv/SCEWIN#7]
![Screenshot 2024-01-11 181743](https://github.com/amitxv/SCEWIN/assets/113597723/e9ffd040-111a-4c97-8fbc-9562c6c3ec71)

works when you edit the setup question like this (to the current set value)

![image](https://github.com/amitxv/SCEWIN/assets/113597723/b0e072c1-17ad-4599-a29c-d532a9f81aaf)

**Comment by amitxv** [comment]
It happens with other vendors, not just MSI. This is due to the setup question containing the current value. I don't recommend changing options such as this and in your case, it is recommended to change timings in UEFI directly.
